### ISSUE TITLE
Option to remove/replace date/time in comments

### ISSUE THREAD

**Issue by christofs** [kappapiana/anonymize#1]
Hi there, very useful and works like a charm! It would be really useful in some scenarios to be able to remove (or replace) the date and time of comments as well, as it is not always desireable to share the timing of each comment, the time between them, and one's work schedule, with others. I realize this would break the "do one thing and do it well" spirit of the script, but seems closely related to the core function. Thanks!

**Comment by kappapiana** [comment]
Thank you. This was born to cover an internal need, that is ex-post anonymize peer-reviewed article, so masking times is also something one would want to do. The principle is identical, one could write a simple search+replace function. It is not rocket science, I am a lousy programmer, maybe you have the opportunity to suggest how to write such function? I am afraid I have neither time nor interest in adding it. But hey, it's Free Software!

**Comment by christofs** [comment]
Fair enough! I'll see what I can do.
