### ISSUE TITLE
Unwanted replacements in document text

### ISSUE THREAD

**Issue by yamanq** [kappapiana/anonymize#19]
Currently, the replace function can also modify text outside of the comment author (comment text, document text), which could be unwanted behavior. The replace function should be expanded with some kind of helper that integrates the search regex into the actual replacement. Ideally, the replace function would be generalized to allow for multiple types of tags rather than just comments. One step towards this would be converting the regex variables into a dictionary of regex expressions so that they can be programmatically accessed. This would also help minimize code duplication across delete_initials, delete_dates, and replace. I imagine the function signature would look something like this:
```def replace(self, from_string, to_string, expression_type)```

**Comment by kappapiana** [comment]
A) your idea to create a dictionary seems cool

B) How can possibly these regexp target stuff outside? They are not much greedy and so far include tags that are not found elsewhere, as per my analysis. But if we find a way to be more selective, I'm fine with it.

**Comment by yamanq** [comment]
I think the initial search for comments is specific enough, but the replace function only takes the author name, without the surrounding tag. Here is an example where I replace "Unknown Author" with "Anonymized Author"
![image](https://user-images.githubusercontent.com/8166212/154335905-d347a4ea-23d2-48a0-a5b8-7e49dcec29dc.png)
![image](https://user-images.githubusercontent.com/8166212/154335960-1bbac28f-6f9a-4929-9243-772ebb1ce246.png)

**Comment by kappapiana** [comment]
You are right.   I thought I had tackled this issue, months ago, probably in my dreams only.
