### ISSUE TITLE
Support NO_COLOR environment variable

### ISSUE THREAD

**Issue by yamanq** [kappapiana/anonymize#21]
It shouldn't be too difficult to implement [this](https://no-color.org/) (without using an external library).

I think a simple solution would be to check for the variable at program start ([os.environ.get()](https://docs.python.org/3/library/os.html#os.environ)) and then override the colors to empty strings.

**Comment by kappapiana** [comment]
Or perhaps we can avoid using colors at all, not sure they add much.
