### ISSUE TITLE
Does not anonymize changes in footnotes

### ISSUE THREAD

**Issue by JohannesNE** [kappapiana/anonymize#22]
Thank you for creating this script!

A small issue:
Changes in footnotes in a .docx file were not anonymized.

**Comment by kappapiana** [comment]
Thank you for noticing. Will look into it.

**Comment by kappapiana** [comment]
@JohannesNE the patch in #23  should fix it. Would you please check if it works? Thank you.

**Comment by JohannesNE** [comment]
Yep, that works! At least for my case.

**Comment by kappapiana** [comment]
Easy when you know where to look. @yamanq was very kind refactoring the entire job to make it more maintainable (and by doing a lot more). It goes to `master` right away
